name: Terraform Cloud Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Plan
        id : plan
        run: terraform plan -input=false -out=tfplan -var-file="vars/prod.tfvars"

      # - name: Terraform Apply
      #   if: ${{ github.ref == 'refs/heads/main' }} # Only apply on the main branch
      #   env:
      #     TF_WORKSPACE: ${{ env.TF_WORKSPACE }}
      #   run: terraform apply -input=false -auto-approve tfplan -var-file=vars/prod.tfvars"
