name: Terraform Cloud Workflow

on:
  push:
    branches:
      - main

env:
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  terraform:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6

      - name: Configure Terraform Cloud
        env:
          TF_API_TOKEN: ${{ env.TF_API_TOKEN }}
        run: terraform login -token=${TF_API_TOKEN}

      - name: Terraform Plan
        id: plan
        env:
          TF_WORKSPACE: ${{ env.TF_WORKSPACE }}
        run: terraform plan -input=false -out=tfplan -var-file=vars/prod.tfvars"

      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/main' }} # Only apply on the main branch
        env:
          TF_WORKSPACE: ${{ env.TF_WORKSPACE }}
        run: terraform apply -input=false -auto-approve tfplan -var-file=vars/prod.tfvars"
